### PR TITLE
Fix 500 error on branch save: move dontCreateBranch into config object

### LINKED ISSUE #804: HTTP 500 on save to user branch + HTTP 404s for en_ta content on working branch (v2.4.10)
## Bug Report

**App Version:** v2.4.10 (build `4c6b89b`)

## Summary

Two related errors occur during a save operation after a "Card To Merge" dialog (merge from master) is presented:

1. **HTTP 500** — `saveChangesToCloud()` fails to upload to the user branch
2. 2. **HTTP 404s** — `useTsvItems` cannot fetch Translation Academy (en_ta) articles from the working branch `deferredreward-tc-create-1` on git.door43.org
## Observed Behavior

- A "Card To Merge" dialog is shown prompting the user to resolve a merge from master.
- - On attempting to save, a **HTTP 500** error is returned: _Failed to upload to user branch_.
- - - `saveChangesToCloud()` retries after the 500 failure (diff visible in console logs).
- - - - Multiple **HTTP 404** warnings from `useTsvItems` when trying to fetch Translation Academy articles (e.g. `figs-metaphor`, `figs-abstractnouns`, `figs-explicit`, etc.) from branch `deferredreward-tc-create-1`.
## Likely Root Cause

- The 500 error on upload suggests the server-side branch push is failing.
- - The 404s suggest the working branch `deferredreward-tc-create-1` may be missing `en_ta` (Translation Academy) content referenced by the translation notes.
- - - These two issues may or may not be related.
## Key Dependencies to Investigate

| Package | Version | Relevance |
|---|---|---|
| `scripture-resources-rcl` | v6.6.1 | Likely contains `saveChangesToCloud` |
| `translation-helps-rcl` | v3.6.8 | Likely contains `useTsvItems` |
| `gitea-react-toolkit` | v2.4.0 | Handles the git push/upload |

## Steps to Reproduce

1. Open a translation note card that references Translation Academy articles.
2. 2. Trigger a merge from master (Card To Merge dialog appears).
3. 3. Attempt to save changes.
4. 4. Observe HTTP 500 in console on save, and HTTP 404s for en_ta resources.
## Console Evidence

- `saveChangesToCloud()` 500 failure with retry and diff logged to console.
- - `useTsvItems` 404s for multiple TA articles on branch `deferredreward-tc-create-1` at `git.door43.org`.

### PR DESCRIPTION
**Pull request by deferredreward**
The `dontCreateBranch: true` flag was passed as a separate prop to `useEdit`, but `useEdit` only forwards the `config` object to `updateContent()`, where `config.dontCreateBranch` is actually checked. Since it wasn't inside `config`, it was always undefined, causing the save fallback to attempt creating a branch that already exists — triggering an HTTP 500 from the Gitea API.

Also adds missing `await` on `saveEdit()` call during branch creation to prevent race conditions.

Closes #804

# Describe what your pull request addresses

- [x] Fixes HTTP 500 error when saving to user branch caused by `dontCreateBranch` not being correctly passed inside the `config` object to `useEdit`/`updateContent()`
- [x] Adds missing `await` on `saveEdit()` during branch creation to prevent race conditions

## Test Instructions

- [ ] Open a translation note card on a branch that already exists
- [ ] Trigger a Card To Merge / merge from master scenario
- [ ] Attempt to save — verify no HTTP 500 occurs and the save completes successfully

### CODE REVIEW

File: src/components/ResourceCard.jsx [hunk 1]
```diff
@@ -350,13 +350,13 @@ export default function ResourceCard({
       ...authentication?.config,
       token: authentication?.token,
       timeout: SERVER_MAX_WAIT_TIME_RETRY,
+      dontCreateBranch: true,
```
Comment (PhotoNomad0) [inline src/components/ResourceCard.jsx:353]: AI caught a 3yo bug

File: src/components/ResourceCard.jsx [hunk 2]
```diff
@@ -443,7 +443,7 @@ export default function ResourceCard({
       const branch = await startEdit()
 
       if (branch) {
-        saveEdit(branch, newContent)
+        await saveEdit(branch, newContent)
```
Comment (PhotoNomad0) [inline src/components/ResourceCard.jsx:446]: doesn't make much difference since there are no further instructions on this if/then/else tree, but it is more consistent and less inclined to future bugs.

**Review by PhotoNomad0 — APPROVED** [review]

**Comment by PhotoNomad0** [comment]
@elsylambert this fix is in latest develop build
